name: Deploy node app to production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t tamiraa468/mern-front:latest --build-arg REACT_APP_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .
      - name: Publish Docker image
        run: docker push tamiraa468/mern-front:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: |
          if ! docker pull tamiraa468/mern-front:latest; then
            echo "Failed to pull image"
            exit 1
          fi
      - name: Delete old Docker container
        run: docker rm -f mern-front || true
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name mern-front tamiraa468/mern-front:latest
      - name: Clean up old Docker images
        if: always()
        run: docker image prune -af
